version: "3"
services:
    redis:
        image: redis:alpine
        ports:
            - "5351:6379"
        command: redis-server


    postgres:
      image: postgres:alpine
      env_file:
        - .env
      volumes:
        - ../2. Init Database:/docker-entrypoint-initdb.d
        - db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G

    bot:
        build: .
        depends_on:
            - redis
            - postgres
        env_file:
            - .env
        command: python main.py

volumes:
    db-data: